// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks-staging/chase-test-4-sample-sdk/pkg/models/shared"
	"io"
	"net/http"
)

type GeneratePostmanCollectionForAPIEndpointRequest struct {
	// The ID of the ApiEndpoint to generate a Postman collection for.
	APIEndpointID string `pathParam:"style=simple,explode=false,name=apiEndpointID"`
	// The ID of the Api to generate a Postman collection for.
	APIID string `pathParam:"style=simple,explode=false,name=apiID"`
	// The version ID of the Api to generate a Postman collection for.
	VersionID string `pathParam:"style=simple,explode=false,name=versionID"`
}

func (o *GeneratePostmanCollectionForAPIEndpointRequest) GetAPIEndpointID() string {
	if o == nil {
		return ""
	}
	return o.APIEndpointID
}

func (o *GeneratePostmanCollectionForAPIEndpointRequest) GetAPIID() string {
	if o == nil {
		return ""
	}
	return o.APIID
}

func (o *GeneratePostmanCollectionForAPIEndpointRequest) GetVersionID() string {
	if o == nil {
		return ""
	}
	return o.VersionID
}

type GeneratePostmanCollectionForAPIEndpointResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Default error response
	Error *shared.Error
	// OK
	// The Close method must be called on this field, even if it is not used, to prevent resource leaks.
	PostmanCollection io.ReadCloser
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GeneratePostmanCollectionForAPIEndpointResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GeneratePostmanCollectionForAPIEndpointResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *GeneratePostmanCollectionForAPIEndpointResponse) GetPostmanCollection() io.ReadCloser {
	if o == nil {
		return nil
	}
	return o.PostmanCollection
}

func (o *GeneratePostmanCollectionForAPIEndpointResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GeneratePostmanCollectionForAPIEndpointResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
