// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks-staging/chase-test-4-sample-sdk/pkg/models/shared"
	"io"
	"net/http"
)

type GenerateRequestPostmanCollectionRequest struct {
	// The ID of the request to retrieve.
	RequestID string `pathParam:"style=simple,explode=false,name=requestID"`
}

func (o *GenerateRequestPostmanCollectionRequest) GetRequestID() string {
	if o == nil {
		return ""
	}
	return o.RequestID
}

type GenerateRequestPostmanCollectionResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Default error response
	Error *shared.Error
	// OK
	// The Close method must be called on this field, even if it is not used, to prevent resource leaks.
	PostmanCollection io.ReadCloser
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GenerateRequestPostmanCollectionResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GenerateRequestPostmanCollectionResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *GenerateRequestPostmanCollectionResponse) GetPostmanCollection() io.ReadCloser {
	if o == nil {
		return nil
	}
	return o.PostmanCollection
}

func (o *GenerateRequestPostmanCollectionResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GenerateRequestPostmanCollectionResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
