// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks-staging/chase-test-4-sample-sdk/pkg/models/shared"
	"net/http"
)

type InsertVersionMetadataRequest struct {
	// A JSON representation of the metadata to insert.
	VersionMetadataInput shared.VersionMetadataInput `request:"mediaType=application/json"`
	// The ID of the Api to insert metadata for.
	APIID string `pathParam:"style=simple,explode=false,name=apiID"`
	// The version ID of the Api to insert metadata for.
	VersionID string `pathParam:"style=simple,explode=false,name=versionID"`
}

func (o *InsertVersionMetadataRequest) GetVersionMetadataInput() shared.VersionMetadataInput {
	if o == nil {
		return shared.VersionMetadataInput{}
	}
	return o.VersionMetadataInput
}

func (o *InsertVersionMetadataRequest) GetAPIID() string {
	if o == nil {
		return ""
	}
	return o.APIID
}

func (o *InsertVersionMetadataRequest) GetVersionID() string {
	if o == nil {
		return ""
	}
	return o.VersionID
}

type InsertVersionMetadataResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Default error response
	Error *shared.Error
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	VersionMetadata *shared.VersionMetadata
}

func (o *InsertVersionMetadataResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *InsertVersionMetadataResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *InsertVersionMetadataResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *InsertVersionMetadataResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *InsertVersionMetadataResponse) GetVersionMetadata() *shared.VersionMetadata {
	if o == nil {
		return nil
	}
	return o.VersionMetadata
}
