// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks-staging/chase-test-4-sample-sdk/pkg/models/shared"
	"net/http"
)

type UpsertAPIRequest struct {
	// A JSON representation of the Api to upsert
	APIInput shared.APIInput `request:"mediaType=application/json"`
	// The ID of the Api to upsert.
	APIID string `pathParam:"style=simple,explode=false,name=apiID"`
}

func (o *UpsertAPIRequest) GetAPIInput() shared.APIInput {
	if o == nil {
		return shared.APIInput{}
	}
	return o.APIInput
}

func (o *UpsertAPIRequest) GetAPIID() string {
	if o == nil {
		return ""
	}
	return o.APIID
}

type UpsertAPIResponse struct {
	// OK
	API *shared.API
	// HTTP response content type for this operation
	ContentType string
	// Default error response
	Error *shared.Error
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *UpsertAPIResponse) GetAPI() *shared.API {
	if o == nil {
		return nil
	}
	return o.API
}

func (o *UpsertAPIResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UpsertAPIResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *UpsertAPIResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UpsertAPIResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
