// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// An EmbedAccessTokenResponse contains a token that can be used to embed a Speakeasy dashboard.
type EmbedAccessTokenResponse struct {
	AccessToken string `json:"access_token"`
}

func (o *EmbedAccessTokenResponse) GetAccessToken() string {
	if o == nil {
		return ""
	}
	return o.AccessToken
}
