// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type GenerateOpenAPISpecDiff struct {
	CurrentSchema string `json:"current_schema"`
	NewSchema     string `json:"new_schema"`
}

func (o *GenerateOpenAPISpecDiff) GetCurrentSchema() string {
	if o == nil {
		return ""
	}
	return o.CurrentSchema
}

func (o *GenerateOpenAPISpecDiff) GetNewSchema() string {
	if o == nil {
		return ""
	}
	return o.NewSchema
}
