// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-sdks-staging/chase-test-4-sample-sdk/pkg/utils"
	"time"
)

// VersionMetadataInput - A set of keys and associated values, attached to a particular version of an Api.
type VersionMetadataInput struct {
	// The key for this metadata.
	MetaKey string `json:"meta_key"`
	// One of the values for this metadata.
	MetaValue string `json:"meta_value"`
}

func (o *VersionMetadataInput) GetMetaKey() string {
	if o == nil {
		return ""
	}
	return o.MetaKey
}

func (o *VersionMetadataInput) GetMetaValue() string {
	if o == nil {
		return ""
	}
	return o.MetaValue
}

// VersionMetadata - A set of keys and associated values, attached to a particular version of an Api.
type VersionMetadata struct {
	// The ID of the Api this Metadata belongs to.
	APIID string `json:"api_id"`
	// Creation timestamp.
	CreatedAt time.Time `json:"created_at"`
	// The key for this metadata.
	MetaKey string `json:"meta_key"`
	// One of the values for this metadata.
	MetaValue string `json:"meta_value"`
	// The version ID of the Api this Metadata belongs to.
	VersionID string `json:"version_id"`
	// The workspace ID this Metadata belongs to.
	WorkspaceID string `json:"workspace_id"`
}

func (v VersionMetadata) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *VersionMetadata) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *VersionMetadata) GetAPIID() string {
	if o == nil {
		return ""
	}
	return o.APIID
}

func (o *VersionMetadata) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *VersionMetadata) GetMetaKey() string {
	if o == nil {
		return ""
	}
	return o.MetaKey
}

func (o *VersionMetadata) GetMetaValue() string {
	if o == nil {
		return ""
	}
	return o.MetaValue
}

func (o *VersionMetadata) GetVersionID() string {
	if o == nil {
		return ""
	}
	return o.VersionID
}

func (o *VersionMetadata) GetWorkspaceID() string {
	if o == nil {
		return ""
	}
	return o.WorkspaceID
}
